list: $/concreta/shorturl/models/shorturl/columns.yaml
modelClass: Concreta\Shorturl\Models\ShortURL
title: ShortURLController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'concreta/shorturl/shorturlcontroller/update/:id'
